id: P009493
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:41:16.782031
source_metadata:
  id: bdr:W1KG16139
  title: ཕར་ཕྱིན་མཐའ་དཔྱོད་མཁས་པའི་མགུལ་རྒྱན།
  author: ''
  volumes:
    52a2a5d5a46d4590ad2aa81e2906ec16:
      image_group_id: I1KG16144
      title: ''
      volume_number: 1
      total_pages: 378
      base_file: v001.txt
    ebbac3b2ffa243e194be3330e6b23015:
      image_group_id: I1KG16145
      title: ''
      volume_number: 2
      total_pages: 442
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
