id: IE7E9C4FD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:27:25+00:00'
last_modified: '2022-06-08T11:25:31.701378+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16139
  title: ཕར་ཕྱིན་མཐའ་དཔྱོད་མཁས་པའི་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2662':
      image_group_id: I1KG16144
      title: ''
      total_pages: 378
      order: 1
      base_file: 2662.txt
    EE4C:
      image_group_id: I1KG16145
      title: ''
      total_pages: 442
      order: 2
      base_file: EE4C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
